### ISSUE TITLE
Getting (MemLock) "Cannot Allocate Memory" on LockedBuf::with_size()

### ISSUE THREAD

**Issue by theli-ua** [glebpom/linux-aio-tokio#23]
Any idea on how to debug this? I'm requesting a fairly small size ~200000

**Comment by glebpom** [comment]
Could be some OS limits. Take a look here: https://stackoverflow.com/questions/27634109/why-mmap-cannot-allocate-memory

**Comment by theli-ua** [comment]
Its from lock, not mmap. 

Either way I figured, Its a user limit on locked memory in my case. ( ulimit -l )

**Comment by theli-ua** [comment]
Would it possible to make LockedBuf a trait so that a user could provide a different implementation?

**Comment by glebpom** [comment]
What is the goal? Linux AIO requires the memory to be locked so that it never gets swapped out. Any ideas why implementation may be different?

**Comment by theli-ua** [comment]
@glebpom for example someone could maintain its own pool of preallocated mapped regions that they would want to reuse instead of doing an mmap every time
